spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]

weather:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY:default}

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-reflesh-period: 1m    # Dakikada 10 tane istek atabilir.
        limit-duration: 10s         #10 saniye bekledikten sonra tekrar istek atmaya devam edebilir