spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]

weather:
  api-url: http://api.weatherstack.com/current
  api-key: ${API-KEY:default}

